#define PEBBLE_STATUS_KEY 1U
#define PEBBLE_ERROR_KEY 2U
#define PEBBLE_RESULT_START_KEY 10U
#define PEBBLE_RESULT_END_KEY 200U
#define PEBBLE_RESERVED_FIELDS_PER_RESULT 19U

// What information in PEBBLE_RESERVED_FIELDS_PER_RESULT is what
#define PEBBLE_RESULT_NTH_SATION_NAME 0U 
#define PEBBLE_RESULT_NTH_DELAY 1U
#define PEBBLE_RESULT_NTH_PLATFORM 2U
#define PEBBLE_RESULT_NTH_TO 3U
#define PEBBLE_RESULT_NTH_CATEGORY 4U
#define PEBBLE_RESULT_NTH_DEPARTURE_HOUR 5U
#define PEBBLE_RESULT_NTH_DEPARTURE_MIN 6U
#define PEBBLE_RESULT_NTH_DEPARTURE_DST 7U
#define PEBBLE_RESULT_NTH_DEPARTURE_DAY 8U
#define PEBBLE_RESULT_NTH_DEPARTURE_MONTH 9U